import type { NextPage } from "next";
import { signIn } from "next-auth/react";
import Head from "next/head";

import { FcGoogle } from "react-icons/fc";

const LoginPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Polly - Landing Page</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className="h-screen flex items-center justify-center"
        style={{
          backgroundImage: "radial-gradient(#4b5563 1px, transparent 2px)",
          backgroundSize: "40px 40px",
        }}
      >
        <div className="max-w-5xl">
          <div className="text-center">
            <h1 className="font-extrabold leading-[1.2em] text-5xl md:text-7xl z-40 text-white hero-title shadow">
              Create a <span className="text-blue-600">poll</span> instantly.
            </h1>
            <h1 className="font-bold text-sm px-6 mt-6 mb-6 hero-title z-40 leading-12  text-gray-200  md:text-xl  md:leading-8">
              Want to ask your friends where they should go on Friday night or
              set up a meeting with coworkers? Create a poll and get results
              quickly.
            </h1>
            <button
              onClick={() =>
                signIn("google", {
                  redirect: true,
                  callbackUrl: "/",
                })
              }
              className="flex items-center justify-center w-3/6 md:w-1/5 space-x-2 bg-white text-gray-700 py-2.5  mx-auto rounded-lg font-bold hover:bg-gray-300 hover:text-gray-900 active:bg-gray-200 active:text-black text-sm tracking-wide"
            >
              <FcGoogle className="w-6 h-6" />
              <div>Signin with Google</div>
            </button>
          </div>
        </div>
      </main>
    </>
  );
};

export default LoginPage;
