import type { NextPage } from "next";
import Head from "next/head";
import IndexLayout from "../components/index-layout";
import { TbChevronsRight } from "react-icons/tb";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Polly - Landing Page</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <IndexLayout>
        <main
          className="h-[calc(100vh-7.2rem)] flex items-center justify-center"
          style={{
            backgroundImage: "radial-gradient(#4b5563 1px, transparent 2px)",
            backgroundSize: "40px 40px",
          }}
        >
          <div className="max-w-5xl">
            <div className="text-center">
              <h1 className="font-extrabold leading-[1.2em] text-5xl md:text-7xl z-40 text-white hero-title shadow">
                Create a <span className="text-blue-600">poll</span> instantly.
              </h1>
              <h1 className="font-bold text-sm px-6 mt-6 mb-6 hero-title z-40 leading-12  text-gray-200  md:text-xl  md:leading-8">
                Want to ask your friends where they should go on Friday night or
                set up a meeting with coworkers? Create a poll and get results
                quickly.
              </h1>
              <Link href="/question">
                <div className="flex items-center justify-center w-3/4 md:w-1/4 space-x-2 border border-blue-600 py-2.5  mx-auto rounded-lg text-blue-600 font-bold hover:bg-blue-600 hover:text-white">
                  <div>Create a poll </div>
                  <TbChevronsRight className="w-4 h-4" />
                </div>
              </Link>
            </div>
          </div>
        </main>
      </IndexLayout>
    </>
  );
};

export default Home;
